### ISSUE TITLE
Danger local does not support Gitlab

### ISSUE THREAD

**Issue by jeremiahk** [danger/danger#477] opened 2016-08-26 16:31 UTC
It looks like Danger local does not support Gitlab. It does say `"Danger local requires a repository hosted on GitHub.com or GitHub Enterprise."`. I thought this was related to ticket [#458](https://github.com/danger/danger/issues/458). Another lingering GitHub exclusivity reference, but local doesn't support Gitlab. There may be other issues, but this is the first two I found. 

Here is the logic for Danger to find the merge request number. View the Danger file [here](https://github.com/danger/danger/blob/ac614d470872ba772d1bd43e93b8568089071272/lib/danger/ci_source/local_git_repo.rb#L41)

```ruby
      specific_pr = env["LOCAL_GIT_PR_ID"]
      pr_ref = specific_pr ? "##{specific_pr}" : ""
      pr_command = "log --merges --oneline"

      # get the most recent PR merge
      pr_merge = run_git(pr_command.strip).lines.grep(Regexp.new("Merge pull request " + pr_ref))[0]
```

The regex that finds merge request numbers does not work with the built in commit messages that Gitlab creates. View the Gitlab file [here](https://gitlab.com/gitlab-org/gitlab-ee/blob/master/app/models/merge_request.rb#L563)

```ruby
  def merge_commit_message
    message = "Merge branch '#{source_branch}' into '#{target_branch}'"
    message << "\n\n"
    message << title.to_s
    message << "\n\n"
    message << description.to_s
    message << "\n\n"
    message << "See merge request !#{iid}"
    message
  end
```

Dangers regex is looking for `"Merge pull request #[id]"`. 
Gitlab uses the phrase `"See merge request ![id]"`

The second problem is that this line is not in the first line of the commit message. Even if the regex was correct Danger would never find it since it doesn't search through the whole commit message.

**Comment by orta** [comment] 2016-08-26 16:33
Sorry that you put so much time into this, but I'm afraid it's a dupe of  https://github.com/danger/danger/issues/458

I'd happily see some patches for GitLab support, but I expect that most of the work will get wiped out by #382 which is still getting fleshed out

**Closed** 2016-08-26 16:33 UTC
