### ISSUE TITLE
Support non github remotes in danger init

### ISSUE THREAD

**Issue by iainsmith** [danger/danger#469] opened 2016-08-24 11:45 UTC
The `danger init` command assumes you want to use Github as your remote. Ideally this could be reworked to make it trivial to add new providers in the future.

**Comment by orta** [comment] 2016-08-24 11:47
This is a dupe of a part of #458 - which is really about #382 - which would fix this, so I'm gonna close this to avoid dupes

**Closed by orta** 2016-08-24 11:47 UTC
