### ISSUE TITLE
Jenkins danger failing

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#782] opened 2017-04-16 20:31 UTC
# Report

## What did you do?

Run `export ghprbPullId=${PULL_REQUEST_ID} && bundle exec danger`

## What did you expect to happen?

Running Dangerfile For the Jenkins job without skipping. 

## What happened instead?

Danger not running. Getting message `Not a Pull Request - skipping danger run`.

## Your Environment

* Which CI are you running on? *Jenkins*
* Are you running the latest version of Danger? *Yes*
* What is your Dangerfile? 

  ```ruby
  declared_trivial = bitbucket_server.pr_title.include? "#trivial"

  warn("PR is classed as Work in Progress") if bitbucket_server.pr_title.include? "[WIP]"

  warn("Big PR") if git.lines_of_code > 500

  fail("fdescribe left in tests") if `grep -r fdescribe specs/ `.length > 1
  fail("fit left in tests") if `grep -r fit specs/ `.length > 1
  ```

**Comment by orta** [comment] 2017-04-17 14:42
This looks like a dupe of https://github.com/danger/danger/issues/763

I'd recommend adding some logs to danger and verifying what's going on [around these validators](https://github.com/danger/danger/blob/master/lib/danger/danger_core/executor.rb#L51-L64) - the areas of the code base are well unit tested, but maybe there's somewhere where they slip between the gaps at integration

**Closed** 2017-04-17 15:57 UTC
