### ISSUE TITLE
GitHub API rate limit running local

### ISSUE THREAD

**Issue by diogot** [danger/danger#342] opened 2016-07-16 20:01 UTC
I'm getting 403 from GitHub while testing locally, is there anything that i can do to prevent it?

```
GET https://api.github.com/repos/diogot/MyWeight/pulls/2: 403 - API rate limit exceeded for <redacted my ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting (Octokit::TooManyRequests)
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-0.9.0/lib/danger/request_source/github.rb:53:in `fetch_details'
	/Users/diogo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-0.9.0/lib/danger/commands/local.rb:55:in `run'
```

**Comment by orta** [comment] 2016-07-16 20:02
@dbgrandi was working on this this morning - this is a dupe of https://github.com/danger/danger/issues/198 👍

**Closed by orta** 2016-07-16 20:02 UTC
