### ISSUE TITLE
https://danger.systems/: Cert date invalid

### ISSUE THREAD

**Issue by ge-fa** [danger/danger#677] opened 2016-12-08 11:12 UTC
Hi,

Not sure if you're aware of this already, but thought it's better to leave a short note here: The cert used on your website is out of date.

All the best,
Georg

**Comment by orta** [comment] 2016-12-08 12:49
thanks, dupe of https://gitlab.com/danger-systems/danger.systems/issues/108

**Closed by orta** 2016-12-08 12:49 UTC

**Comment by JLLeitschuh** [comment] 2016-12-12 15:54
Still be broke.
http://danger.systems works fine though.
Consider changing the link on the repo title bar till this is fixed?

**Comment by JuanitoFatas** [comment] 2016-12-12 16:03
> Still be broke.
> http://danger.systems works fine though.
> Consider changing the link on the repo title bar till this is fixed?

Changed, thank you! <3
