### ISSUE TITLE
💡 Optionally omitting "All Green" message in BitBucket

### ISSUE THREAD

**Issue by ChristianOrgler** [danger/danger#1299] opened 2021-04-08 09:34 UTC
Some of my colleagues would like to simply not get any message on their PRs if danger ran through without issues (due to notifications triggered by it, etc.)

So I thought it wouldn't hurt to create some kind of flag you can declare in your Dangerfile (opt-in) to omit the "All Green <something>" message completely if there are no errors nor warnings.

Wanted to check here first before trying to open up a pull-request and then get declined because that's nothing someone here would like to have. Let me know and I jump onto the code :)

**Comment by orta** [comment] 2021-04-08 11:16
As in not echo anything to stdout? 

I'm not particularly wild on accepting a flag for it because it feels like a very niche request, perhaps an ENV var documented in the CHANGELOG and a well tested PR would be OK

**Comment by ChristianOrgler** [comment] 2021-04-08 11:52
If errors and warnings are empty (and no code insights etc. are enabled) then don't comment on the pr at all.
Like returning `nil` there if configured (flag or env var, both fine) - https://github.com/danger/danger/blob/24020208d0b7a741cdd741ab1a7dd0295e1bb792/lib/danger/helpers/comments_helper.rb#L151

**Comment by orta** [comment] 2021-04-08 14:02
Why would you want to ignore messages?

**Comment by ChristianOrgler** [comment] 2021-04-08 16:12
The current behaviour we see (we use Bitbucket Server) is that if there are no errors, nor warnings nor additional messages available, Danger writing "All green. <random compliment>"

The feedback from my colleagues was that they would like to not get this comment on the PR at all, only if there is anything to point out from Danger.

**Comment by orta** [comment] 2021-04-08 16:14
Yep cool, that behavior sounds like a bug IMO, the expected behavior is how it works in GitHub etc

Will definitely take a PR fixing that 👍🏻

**Comment by ChristianOrgler** [comment] 2021-04-21 06:49
Are you sure we are speaking about the same thing? Just want to make sure before start creating a pr. Because the generic helper that creates the comment does it (for all vendors) here:
https://github.com/danger/danger/blob/master/lib/danger/helpers/comments_helper.rb#L151

And the generate_comment that gets posted afterwards also always creates a message no matter if there is anything to show or not here:
https://github.com/danger/danger/blob/master/lib/danger/helpers/comments_helper.rb#L95

My suggestion would be to have a flag / env variable (whatever) to be able to do something like this:

```
should_omit_success_msg = ENV["OMIT_SUCCESS_MESSAGE"]
should_omit_success_msg = false if should_omit_success_msg.nil?

if errors.empty? && warnings.empty?
  return "All green. #{random_compliment}" unless should_omit_success_msg
  return ""
(..)
```

or actually should be handled in the generate_comment method, if no errors, warnings, markdowns, messages, etc. are set then don't generate a comment and not post it.

**Comment by orta** [comment] 2021-04-21 07:04
So be to explicit:

This is the message, it should always be there:

![Screen Shot 2021-04-21 at 8 01 00 AM](https://user-images.githubusercontent.com/49038/115510508-bbc52700-a277-11eb-9bc8-a7c77fbcf56e.png)

The PR comment will get deleted if there are no errors/warnings/logs. I'm ok with a PR hiding that with an obscure ENV var if it's a well tested and simple PR, otherwise it's not worth the codebase complexity to me.

**Comment by ChristianOrgler** [comment] 2021-04-21 09:26
On Bitbucket Server this looks like the following, which is an extra comment on the pull request:

![Screenshot 2021-04-21 at 11 24 25](https://user-images.githubusercontent.com/7498210/115530658-41ef6680-a294-11eb-8198-530f37e4a244.png)

We would like to avoid that, if the run through was positive, without any issues. Does that break your view on the behaviour fo the tool? If so, I guess we would have to fork it if we really want to have it. :D

**Comment by orta** [comment] 2021-04-21 09:36
Yeah perfect, I'd totally take a PR dropping that message. Now we're on the same page, hard to keep all the implementations and their constraints in my head.

I assume the creator of the BBS code review implementation didn't add the edit/delete cycle which we have in GitHub, I think dropping the message if it's green is definitely good thing to do 👍🏻 (optimal is having it deleting old messages from the bot too)

**Comment by ChristianOrgler** [comment] 2021-04-21 09:49
Some implementation details to clarify upfront, to make it faster later:

* Do you think the behaviour should be in the BBS implementation code located?
* Do you then still need a flag to be introduced (I guess to not break old behaviour it should) or not?

**Comment by orta** [comment] 2021-04-21 10:13
- I think this is probably only affecting BBS, maybe the GitLab implementation too, but definitely not GitHub - so the change should be localized

- No flag, unless there's some valid historical reason for this

**Comment by ChristianOrgler** [comment] 2021-04-21 11:30
Thanks, will work on it. - Don't think that posting a comment or not can be tested tho in that case - will check.

**Comment by glensc** [comment] 2021-04-27 15:26
Perhaps updating the Issue title, that this is bitbucked specific, is in order?

**Comment by manicmaniac** [comment] 2023-01-29 07:21
Resolved in https://github.com/danger/danger/pull/1331. Let me close this issue.

**Closed by manicmaniac** 2023-01-29 07:21 UTC
