### ISSUE TITLE
gitlab brings in a rarely compatible version of the json gem

### ISSUE THREAD

**Issue by dblock** [danger/danger#521] opened 2016-09-04 00:00 UTC
https://travis-ci.org/ruby-grape/grape-entity/jobs/157378972

```
~/source/grape/grape-entity/dblock (danger)$ bundle update
Fetching gem metadata from http://rubygems.org/
Fetching version metadata from http://rubygems.org/
Fetching dependency metadata from http://rubygems.org/
Resolving dependencies.....
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    json (~> 2.0)

    ruby-grape-danger (~> 0.1.0) was resolved to 0.1.0, which depends on
      danger (~> 3.2.0) was resolved to 3.2.0, which depends on
        gitlab (~> 3.7.0) was resolved to 3.7.0, which depends on
          httparty (~> 0.13.0) was resolved to 0.13.0, which depends on
            json (~> 1.8)
```

The 1.8 version is old, this looks like a big problem as a lot of other things depend on json 2.x.

**Comment by orta** [comment] 2016-09-04 00:01
Gonna call this one a dupe of https://github.com/danger/danger/issues/506 and close it, I was planning on doing this for 4.0

**Closed** 2016-09-04 00:01 UTC

**Comment by dblock** [comment] 2016-09-04 00:02
I don't think it's a dup because you'll still have to deal with this for gitlab support.
