### ISSUE TITLE
Error on git merge-base

### ISSUE THREAD

**Issue by kylejm** [danger/danger#494] opened 2016-08-31 10:02 UTC
```
Git::GitExecuteError: git '--git-dir=/Users/vagrant/git/.git' '--work-tree=/Users/vagrant/git' merge-base 'danger_base' 'danger_head'
```

It seems that the `danger_base` and `danger_head` aren't being populated with commit hashes.

Using 3.1.0 on Bitrise.

**Comment by cysp** [comment] 2016-08-31 10:40
Is the error the same as seen at https://circleci.com/gh/danger/danger.systems/89, referenced from https://github.com/danger/danger/issues/480?

**Comment by orta** [comment] 2016-08-31 12:53
Yeah, I bet it is

**Comment by orta** [comment] 2016-08-31 12:54
Closing as a dupe of #480

**Closed by orta** 2016-08-31 12:54 UTC
