### ISSUE TITLE
NoMethodError: undefined method `merge' for #<Gitlab::ObjectifiedHash:0x000056550fdcea78>

### ISSUE THREAD

**Issue by dmakeienko** [danger/danger#1244] opened 2020-07-14 09:52 UTC
# Report

## What did you do?

ℹ Run danger-rb from latest Docker image crashes

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
  Running your Dangerfile without it crashing.

## What happened instead?

ℹ Bundler couldn't find danger and method `merge`

## Your Environment

* CI: Self-Hosted GitLab Enterprise Edition 11.7.5-ee
* My .gitlab-ci.yml
```
danger_review:
  stage: review
  image: 
    name: dangersystems/danger-rb
    entrypoint: [""]
  script:
    - bundle exec danger --fail-on-errors=true
  only:
    refs:
      - merge_requests
  ```

* Danger version: latest (Docker image)
* My Dangerfile:

```
  #Ensure that all mrs have an assignee.

  warn "This MR does not have any assignees yet." unless gitlab.mr_json["assignee"]

  #Ensure that branch name follows convention

  ## Regular expressions for PR title and branch
  title_pattern =/^([A-Z]{2,})-\d{3,5}:.\w/
  branch_name_pattern = /^([A-Z]{2,})-\d{3,5}/

  branch_contains_jira_id = gitlab.branch_for_head.match(branch_name_pattern)
  title_contains_jira_id = gitlab.pr_title.match(title_pattern)

  fail("Branch name should include JIRA-ID (e.g. ARK-xxxx).") unless branch_contains_jira_id

  fail("MR should include JIRA-ID and short description.") unless title_contains_jira_id
```

* Error during CI
  ```ruby
  $ bundle exec danger --fail-on-errors=true
  bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
  NoMethodError: undefined method `merge' for #<Gitlab::ObjectifiedHash:0x000056550fdcea78>
  /usr/local/bundle/gems/gitlab-4.16.0/lib/gitlab/objectified_hash.rb:37:in `method_missing'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `block (2 levels) in mr_comments'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `map'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `block in mr_comments'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `each'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `flat_map'
  /myapp/lib/danger/request_sources/gitlab.rb:87:in `mr_comments'
  /myapp/lib/danger/request_sources/gitlab.rb:180:in `update_pull_request_with_inline_comments!'
  /myapp/lib/danger/request_sources/gitlab.rb:173:in `update_pull_request!'
  /myapp/lib/danger/danger_core/dangerfile.rb:260:in `post_results'
  /myapp/lib/danger/danger_core/dangerfile.rb:288:in `run'
  /myapp/lib/danger/danger_core/executor.rb:29:in `run'
  /myapp/lib/danger/commands/runner.rb:73:in `run'
  /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /myapp/bin/danger:5:in `<top (required)>'
  /usr/local/bundle/bin/danger:23:in `load'
  /usr/local/bundle/bin/danger:23:in `<top (required)>'
  Running after_script
  Uploading artifacts for failed job
  ERROR: Job failed: exit code 1
  ```
## My additional suggestion
 
  Enable versioning for Docker images so we could provide version directly in case of breaking changes on API

**Comment by orta** [comment] 2020-07-14 11:05
Dupe of #1241

**Closed by orta** 2020-07-14 11:05 UTC
