### ISSUE TITLE
Danger should keep violations order

### ISSUE THREAD

**Issue by marcelofabri** [danger/danger#703] opened 2017-01-22 22:19 UTC
# Report

## What did you do?

Run `danger`.

## What did you expect to happen?

The comment should report violations in the same order as they were reported. This could be related to previous runs of Danger.

## What happened instead?

It didn't respect the order. See [the report on CI](https://circleci.com/gh/realm/SwiftLint/276) vs the [comment on the PR](https://github.com/realm/SwiftLint/pull/1226#issuecomment-274313662).

## Your Environment

* Which CI are you running on? Circle
* Are you running the latest version of Danger? Yep, 4.0.5
* What is your Dangerfile? https://github.com/marcelofabri/SwiftLint/blob/35209910b74c94731cfbb20376876ef6b8d4002d/Dangerfile

**Comment by orta** [comment] 2017-01-22 22:24
Maybe we need a timestamp on the creation of a violation?

**Comment by marcelofabri** [comment] 2017-01-22 22:27
I think this is a simpler issue than that - see that in the Circle log the violations are shown in the expected order. Something between that and reporting have changed it (maybe https://github.com/danger/danger/blob/master/lib/danger/request_sources/github.rb#L136-L139?)

**Comment by marcelofabri** [comment] 2017-01-22 22:57
I've opened https://github.com/realm/SwiftLint/pull/1230 which did a fresh run and it showed the same problem, so it's not an issue edit problem.

**Comment by sleekybadger** [comment] 2017-05-10 08:27
@marcelofabri @orta is this still actual?

I created Dangerfile that simply prints your messages:

```
message('Linting Alamofire with this PR took 3.33s vs 3.32s on master (0% slower)')
message('Linting swift with this PR took 11.55s vs 11.55s on master (0% slower)')
message('Linting Aerial with this PR took 0.43s vs 0.43s on master (0% slower)')
message('Linting SourceKitten with this PR took 1.55s vs 1.54s on master (0% slower)')
message('Linting Sourcery with this PR took 2.27s vs 2.31s on master (1% faster)')
message('Linting ios-oss with this PR took 17.73s vs 17.47s on master (1% slower)')
message('Linting Moya with this PR took 0.47s vs 0.44s on master (6% slower)')
message('Linting firefox-ios with this PR took 16.59s vs 16.57s on master (0% slower)')
message('Linting Nimble with this PR took 1.77s vs 1.8s on master (1% faster)')
message('Linting Quick with this PR took 0.53s vs 0.54s on master (1% faster)')
message('Linting realm-cocoa with this PR took 3.66s vs 3.65s on master (0% slower)')
message('Linting WordPress-iOS with this PR took 7.51s vs 7.48s on master (0% slower)')
```

and result:

![Alt text](https://monosnap.com/file/KfWcMuPAYCkTPxGgo2EkjKZGe4Ljtz.png)

@marcelofabri can you please recheck this with latest version of danger?

**Comment by orta** [comment] 2017-05-10 09:06
Hrm, there's potential that the output for the script generating these results could be passing the messages through in a different order ( as they may take different amounts of time? )

**Comment by marcelofabri** [comment] 2017-05-10 09:12
> Hrm, there's potential that the output for the script generating these results could be passing the messages through in a different order ( as they may take different amounts of time? )

The operations aren't parallel, so I can't see how this would be the case. Also, the order was right when Danger prints the violations to stdout (see https://circleci.com/gh/realm/SwiftLint/276).

> @marcelofabri can you please recheck this with latest version of danger?

I'll try it later, but feel free to try to reproduce it on SwiftLint repo.

**Comment by sleekybadger** [comment] 2017-05-10 09:16
Don't think so. @marcelofabri Dangerfile look quite synchronous and explicit

```
@repos.each do |repo|
    # some code that calculates values
    message "Linting #{repo_name} with this PR took #{branch_duration}s " \
            "vs #{master_duration}s on master (#{percent_change.to_i}\% #{faster_slower})"
  end
```

@marcelofabri thank u, I'll test.

**Comment by sleekybadger** [comment] 2017-05-10 12:54
@orta oh, I find it 

[Here](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L147-L152) we sort violations, then we send inline comments and remove them from sorted arrays. But to github we [push](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L169-L175) without original order.

I think we can just select inline comments and pass them to `submit_inline_comments!` and we will note care about arrays mutation. What do you think about it?

Also i wonder why i can't reproduce this for my example, so I will debug this more in evening.

**Comment by sleekybadger** [comment] 2017-05-10 22:29
@orta fix for this https://github.com/danger/danger/pull/813

**Closed** 2017-05-19 13:05 UTC
Labels: Bug
