### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by markmur** [danger/danger#973] opened 2018-03-26 15:14 UTC
# Report

http://danger.systems is throwing a 404

## What did you do?

Go to http://danger.systems

![screen shot 2018-03-26 at 16 12 32](https://user-images.githubusercontent.com/2034704/37915120-a84c12b4-3110-11e8-9e40-9c4ad796ff9b.png)

**Comment by orta** [comment] 2018-03-26 15:18
Thanks - Dupe of #972 and https://github.com/danger/danger-js/issues/544 is the canonical issue

**Closed by orta** 2018-03-26 15:18 UTC
