### ISSUE TITLE
Support for Bamboo

### ISSUE THREAD

**Issue by kcharwood** [danger/danger#193] opened 2016-05-03 16:55 UTC
I'm looking to providing support for Bamboo, but from what I can tell, Bamboo doesn't offer up the Pull Request number as an environment variable (It builds on commit, not when a PR is generated, and Bitbucket Server and Bamboo talk behind the scenes to link the results).

Is the pull request ID a hard requirement here? What functionality would not be available if that was made optional?

**Comment by orta** [comment] 2016-05-03 16:57
The pull request is needed to be able to get back to the PR to show the body/description and to post. In Circle, we use it's API to get the full PR details based on the commit - maybe bamboo can do that?

**Comment by orta** [comment] 2016-05-03 16:58
https://github.com/danger/danger/blob/master/lib/danger/ci_source/circle.rb#L24

**Comment by orta** [comment] 2016-05-03 16:59
There _may_ be a way via the GitHub API to go from a commit to a PR, don't think we've explored that space either.

**Comment by kcharwood** [comment] 2016-05-03 17:02
Cool. I'll look  that direction and see what I can dig up

**Comment by kcharwood** [comment] 2016-05-03 18:53
@orta If no PR has been created yet, would that prevent Danger from running a per commit build?

**Comment by orta** [comment] 2016-05-03 18:56
It would, this is why we use the Circle API, if Danger is running at the end of a build process it gives it some time. The only platform that definitely won't have the problem is travis-ci as it creates a commit run and a PR run separately.

**Comment by kcharwood** [comment] 2016-05-03 18:57
Gotcha.

Any appetite for making a pull request id optional, and just not expose functionality around validating that if it is not provided?

There are some useful things here I can think I can get out of a per commit build running Danger, but my teams current Bamboo + Bitbucket setup/workflow complicates that too much.

**Comment by jeroenvisser101** [comment] 2016-05-03 19:03
You could actually get it through the GitHub API, by filtering on the base (branch name) ([see this](https://developer.github.com/v3/pulls/#list-pull-requests))

**Comment by orta** [comment] 2016-05-03 19:03
I think this would be cool, yeah, we've tried to decouple a lot of this stuff but never really had a need for it in our own projects. IMO it'd be nice to be able to have it run safely without GitHub - there's been work [on GitLab](https://github.com/danger/danger/pull/59) but it is blocked by GitLab API changes I think.

**Comment by nekrich** [comment] 2020-01-28 11:16
Looks like it's resolved in v6.2.0 in #1172 (Issue #985). Kudos to @Qbeorama .

**Comment by orta** [comment] 2020-01-28 14:29
great POINT

**Closed by orta** 2020-01-28 14:29 UTC
